import os
BASE = r"C:\Users\85932\.qclaw\workspace\software-factory\projects\kouming\lib"
FL = os.path.join(BASE, "features","shop","fate_draw_flow.dart")

TW = '\U0001F38B'  # musical notes emoji
SP = '\U0001F3B4'  # spade flower
WV = '\U00003030'  # wavy dash
OR = '\U0001F52E'  # crystal ball
SH = '\U0001F6E1'  # shield

content = (
"import 'dart:math';\n"
"import 'package:flutter/material.dart';\n"
"import 'package:kouming/shared/theme/kouming_theme.dart';\n"
"import 'package:kouming/shared/models/kouming_models.dart';\n"
"import 'package:kouming/services/i18n_service.dart';\n"
"\n"
"class FateDrawFlow extends StatefulWidget {\n"
"  final VoidCallback onDrawComplete;\n"
"  final VoidCallback onPaymentRequired;\n"
"  const FateDrawFlow({super.key, required this.onDrawComplete, required this.onPaymentRequired});\n"
"  static Future<void> show(BuildContext context, {required VoidCallback onDrawComplete, required VoidCallback onPaymentRequired}) {\n"
"    return showModalBottomSheet(context: context, isScrollControlled:true, backgroundColor:Colors.transparent,\n"
"      builder:(_)=>FateDrawFlow(onDrawComplete:onDrawComplete, onPaymentRequired:onPaymentRequired));\n"
"  }\n"
"  @override State<FateDrawFlow> createState() => _FateDrawFlowState();\n"
"}\n"
"\n"
"class _FateDrawFlowState extends State<FateDrawFlow> with TickerProviderStateMixin {\n"
"  late AnimationController _shakeCtrl, _flyCtrl, _flipCtrl;\n"
"  _Phase _phase = _Phase.idle;\n"
"  FortuneSlip? _result;\n"
"\n"
"  @override void initState() {\n"
"    super.initState();\n"
"    _shakeCtrl = AnimationController(vsync:this, duration: const Duration(milliseconds:1500));\n"
"    _flyCtrl = AnimationController(vsync:this, duration: const Duration(milliseconds:800));\n"
"    _flipCtrl = AnimationController(vsync:this, duration: const Duration(milliseconds:800));\n"
"    _flyCtrl.addStatusListener((s){ if(s==AnimationStatus.completed){ setState(()=>_phase=_Phase.reveal); _flipCtrl.forward(); }});\n"
"  }\n"
"  @override void dispose() { _shakeCtrl.dispose(); _flyCtrl.dispose(); _flipCtrl.dispose(); super.dispose(); }\n"
"\n"
"  FortuneSlip _drawFortune() {\n"
"    final rng = Random();\n"
"    final roll = rng.nextDouble();\n"
"    final level = roll<0.05?FortuneLevel.supreme:roll<0.25?FortuneLevel.great:roll<0.60?FortuneLevel.medium:roll<0.85?FortuneLevel.low:FortuneLevel.bad;\n"
"    return _fortunePool[level]![rng.nextInt(_fortunePool[level]!.length)];\n"
"  }\n"
"\n"
"  void _startDraw() {\n"
"    _result = _drawFortune();\n"
"    setState(()=>_phase=_Phase.shaking);\n"
"    _shakeCtrl.forward().then((_){ setState(()=>_phase=_Phase.flying); _flyCtrl.forward(from:0); });\n"
"  }\n"
"\n"
"  @override Widget build(BuildContext context) {\n"
"    return Container(height: MediaQuery.of(context).size.height*0.75,\n"
"      decoration: const BoxDecoration(gradient:LinearGradient(begin:Alignment.topCenter,end:Alignment.bottomCenter,colors:[KouMingTheme.deep,KouMingTheme.mid]),\n"
"        borderRadius: BorderRadius.vertical(top:Radius.circular(24))),\n"
"      child: Column(children: [\n"
"        Center(child:Container(margin: const EdgeInsets.only(top:10), width:40, height:4,\n"
"          decoration: BoxDecoration(color:KouMingTheme.gold.withValues(alpha:0.3), borderRadius:BorderRadius.circular(2)))),\n"
"        const SizedBox(height:12),\n"
"        Text(SP + ' ' + I18n.t('fate_title'), style: const TextStyle(fontSize:20, fontWeight:FontWeight.bold, color:KouMingTheme.gold, fontFamily:'MaShanZheng')),\n"
"        const SizedBox(height:20),\n"
"        Expanded(child:_buildContent()),\n"
"      ]));\n"
"  }\n"
"\n"
"  Widget _buildContent() {\n"
"    switch(_phase){ case _Phase.idle: return _buildIdle(); case _Phase.shaking: return _buildShaking(); case _Phase.flying: return _buildFlying(); case _Phase.reveal: return _buildReveal(); }\n"
"  }\n"
"\n"
"  Widget _buildIdle() {\n"
"    return Center(child: Column(mainAxisSize:MainAxisSize.min, children:[\n"
"      Container(width:120, height:160, decoration: BoxDecoration(gradient:const LinearGradient(colors:[KouMingTheme.warm,KouMingTheme.gold]),\n"
"        borderRadius:BorderRadius.circular(16), border:Border.all(color:KouMingTheme.gold,width:2),\n"
"        boxShadow:[BoxShadow(color:KouMingTheme.gold.withValues(alpha:0.2),blurRadius:20)]),\n"
"        child: Center(child:Text(TW,style:TextStyle(fontSize:48)))),\n"
"      const SizedBox(height:24),\n"
"      Text(I18n.t('fate_shake_hint'), style: const TextStyle(fontSize:13, color:KouMingTheme.dim)),\n"
"      const SizedBox(height:16),\n"
"      GestureDetector(onTap:_startDraw,\n"
"        child: Container(padding: const EdgeInsets.symmetric(horizontal:32,vertical:14),\n"
"          decoration: BoxDecoration(gradient:const LinearGradient(colors:[KouMingTheme.gold,KouMingTheme.warm]),\n"
"            borderRadius:BorderRadius.circular(24), boxShadow:[BoxShadow(color:KouMingTheme.gold.withValues(alpha:0.3),blurRadius:12)]),\n"
"          child: Text(I18n.t('fate_draw_btn'), style: const TextStyle(fontSize:15, fontWeight:FontWeight.bold, color:Color(0xFF1A1A2E))))),\n"
"    ]));\n"
"  }\n"
"\n"
"  Widget _buildShaking() {\n"
"    return Center(child: AnimatedBuilder(animation:_shakeCtrl, builder:(ctx,child){\n"
"      final t = _shakeCtrl.value;\n"
"      final angle = sin(t*8*pi)*0.15*(1-t);\n"
"      final offsetX = sin(t*12*pi)*8*(1-t);\n"
"      return Transform.translate(offset:Offset(offsetX,0), child: Transform.rotate(angle:angle, child:child));\n"
"    }, child: Container(width:120, height:160, decoration: BoxDecoration(gradient:const LinearGradient(colors:[KouMingTheme.warm,KouMingTheme.gold]),\n"
"      borderRadius:BorderRadius.circular(16), border:Border.all(color:KouMingTheme.gold,width:2),\n"
"      boxShadow:[BoxShadow(color:KouMingTheme.gold.withValues(alpha:0.4),blurRadius:30)]),\n"
"      child: Stack(alignment:Alignment.center, children:[\n"
"        Center(child:Text(TW,style:TextStyle(fontSize:48))),\n"
"        Positioned(top:8,left:30,child:Transform.rotate(angle:-0.2,child:Text(WV,style:TextStyle(fontSize:20,color:KouMingTheme.gold.withValues(alpha:0.6)))))),\n"
"        Positioned(top:12,right:28,child:Transform.rotate(angle:0.15,child:Text(WV,style:TextStyle(fontSize:18,color:KouMingTheme.gold.withValues(alpha:0.5)))))),\n"
"      ]))));\n"
"  }\n"
"\n"
"  Widget _buildFlying() {\n"
"    return AnimatedBuilder(animation:_flyCtrl, builder:(ctx,_){\n"
"      final t = _flyCtrl.value;\n"
"      final y = 80 - Curves.easeOut.transform(t)*160;\n"
"      final scale = 0.6 + Curves.easeOut.transform(t)*0.4;\n"
"      final opacity = 0.5 + t*0.5;\n"
"      return Center(child: Transform.translate(offset:Offset(0,y),\n"
"        child: Transform.scale(scale:scale, child:Opacity(opacity:opacity, child:_buildStickCard(back:true))))));\n"
"    });\n"
"  }\n"
"\n"
"  Widget _buildStickCard({required bool back}) {\n"
"    return Container(width:80, height:180, decoration: BoxDecoration(\n"
"      gradient: back ? const LinearGradient(colors:[Color(0xFF8B0000),Color(0xFFB22222)]) : LinearGradient(colors:[_levelColor(_result!.level).withValues(alpha:0.3), KouMingTheme.surface]),\n"
"      borderRadius:BorderRadius.circular(12), border:Border.all(color:back?KouMingTheme.lantern:_levelColor(_result!.level),width:2),\n"
"      boxShadow:[BoxShadow(color:(back?KouMingTheme.lantern:_levelColor(_result!.level)).withValues(alpha:0.4),blurRadius:20)]),\n"
"      child: back ? Center(child:Text('ы',style:TextStyle(fontSize:36,color:KouMingTheme.gold,fontFamily:'MaShanZheng'))) : _buildFortuneContent());\n"
"  }\n"
"\n"
"  Widget _buildFortuneContent() {\n"
"    if(_result==null) return const SizedBox.shrink();\n"
"    return Padding(padding: const EdgeInsets.all(12), child: Column(mainAxisAlignment:MainAxisAlignment.center, children:[\n"
"      Text(_result!.emoji, style: const TextStyle(fontSize:28)),\n"
"      const SizedBox(height:6),\n"
"      Text(_result!.title, style:TextStyle(fontSize:14,fontWeight:FontWeight.bold,color:_levelColor(_result!.level),fontFamily:'MaShanZheng'), textAlign:TextAlign.center),\n"
"      const SizedBox(height:4),\n"
"      Text(_levelLabel(_result!.level), style:TextStyle(fontSize:11,color:_levelColor(_result!.level))),\n"
"    ]));\n"
"  }\n"
"\n"
"  Widget _buildReveal() {\n"
"    if(_result==null) return const SizedBox.shrink();\n"
"    return AnimatedBuilder(animation:_flipCtrl, builder:(ctx,_){\n"
"      final t = _flipCtrl.value;\n"
"      final angle = t<0.5 ? t*pi : (t-1)*pi;\n"
"      final showFront = t>=0.5;\n"
"      return Center(child: Column(mainAxisSize:MainAxisSize.min, children:[\n"
"        Transform(alignment:Alignment.center, transform:Matrix4.identity()..setEntry(3,2,0.001)..rotateY(angle),\n"
"          child: showFront ? _buildFullResultCard() : _buildStickCard(back:true)),\n"
"      ]));\n"
"    });\n"
"  }\n"
"\n"
"  Widget _buildFullResultCard() {\n"
"    final color = _levelColor(_result!.level);\n"
"    return Container(width:260, padding: const EdgeInsets.all(24),\n"
"      decoration: BoxDecoration(gradient:LinearGradient(colors:[color.withValues(alpha:0.15),KouMingTheme.surface]),\n"
"        borderRadius:BorderRadius.circular(20), border:Border.all(color:color,width:2),\n"
"        boxShadow:[BoxShadow(color:color.withValues(alpha:0.3),blurRadius:24)]),\n"
"      child: Column(mainAxisSize:MainAxisSize.min, children:[\n"
"        Container(padding: const EdgeInsets.symmetric(horizontal:16,vertical:4),\n"
"          decoration: BoxDecoration(color:color.withValues(alpha:0.2), borderRadius:BorderRadius.circular(12), border:Border.all(color:color.withValues(alpha:0.5))),\n"
"          child: Text(_levelLabel(_result!.level), style:TextStyle(fontSize:13,fontWeight:FontWeight.bold,color:color))),\n"
"        const SizedBox(height:16),\n"
"        Text(_result!.emoji, style: const TextStyle(fontSize:40)),\n"
"        const SizedBox(height:12),\n"
"        Text(_result!.title, style:TextStyle(fontSize:22,fontWeight:FontWeight.bold,color:color,fontFamily:'MaShanZheng')),\n"
"        const SizedBox(height:8),\n"
"        Text(_result!.description, style: const TextStyle(fontSize:12,color:KouMingTheme.text,height:1.6), textAlign:TextAlign.center),\n"
"        const SizedBox(height:12),\n"
"        Row(mainAxisAlignment:MainAxisAlignment.center, children:[\n"
"          Text(OR + ' ', style:TextStyle(fontSize:12)),\n"
"          Text(I18n.t('fate_element') + _result!.element, style:TextStyle(fontSize:11,color:color.withValues(alpha:0.8))),\n"
"          const SizedBox(width:12),\n"
"          Text(SH + ' ', style:TextStyle(fontSize:12)),\n"
"          Text(I18n.t('fate_guardian') + _result!.guardian, style:TextStyle(fontSize:11,color:color.withValues(alpha:0.8))),\n"
"        ]),\n"
"        const SizedBox(height:20),\n"
"        GestureDetector(onTap:(){ widget.onDrawComplete(); Navigator.pop(context); },\n"
"          child: Container(padding: const EdgeInsets.symmetric(horizontal:24,vertical:10),\n"
"            decoration: BoxDecoration(gradient:LinearGradient(colors:[color,color.withValues(alpha:0.7)]), borderRadius:BorderRadius.circular(16)),\n"
"            child: Text(I18n.t('fate_accept'), style: const TextStyle(fontSize:13,fontWeight:FontWeight.bold,color:KouMingTheme.deep)))),\n"
"      ]));\n"
"  }\n"
"\n"
"  static Color _levelColor(FortuneLevel level) {\n"
"    switch(level){ case FortuneLevel.supreme: return KouMingTheme.gold; case FortuneLevel.great: return KouMingTheme.lantern;\n"
"      case FortuneLevel.medium: return KouMingTheme.purple; case FortuneLevel.low: return KouMingTheme.water; case FortuneLevel.bad: return const Color(0xFF666688); }\n"
"  }\n"
"\n"
"  String _levelLabel(FortuneLevel level) {\n"
"    switch(level){ case FortuneLevel.supreme: return I18n.t('fortune_supreme'); case FortuneLevel.great: return I18n.t('fortune_great');\n"
"      case FortuneLevel.medium: return I18n.t('fortune_medium'); case FortuneLevel.low: return I18n.t('fortune_low'); case FortuneLevel.bad: return I18n.t('fortune_bad'); }\n"
"  }\n"
'\n'
"  static const Map<FortuneLevel,List<FortuneSlip>> _fortunePool = {\n"
"    FortuneLevel.supreme: [\n"
"      FortuneSlip(title:'天赐鸿运',description:'万事如意，心想事成。天时地利人和，此时正是最好的时机。',emoji:'*',level:FortuneLevel.supreme,element:'金',guardian:'白虎'),\n"
"      FortuneSlip(title:'紫气东来',description:'祥瑞降临，好运连连。贵人在侧，诸事顺遂。',emoji:'+',level:FortuneLevel.supreme,element:'火',guardian:'朱雀'),\n"
"    ],\n"
"    FortuneLevel.great: [\n"
"      FortuneSlip(title:'否极泰来',description:'低谷已过，曙光初现。坚持本心，必有转机。',emoji:'o',level:FortuneLevel.great,element:'木',guardian:'青龙'),\n"
"      FortuneSlip(title:'贵人相助',description:'有人暗中助力，事半而功倍。保持开放心态，接纳帮助。',emoji:'#',level:FortuneLevel.great,element:'土',guardian:'麒麟'),\n"
"      FortuneSlip(title:'锦上添花',description:'好事之上更有好事，正逢顺水推舟之时。',emoji:'~',level:FortuneLevel.great,element:'水',guardian:'玄武'),\n"
"    ],\n"
"    FortuneLevel.medium: [\n"
"      FortuneSlip(title:'守中持平',description:'不急不躁，稳中求进。此时宜守不宜攻，静待时机。',emoji:'-',level:FortuneLevel.medium,element:'土',guardian:'勾陈'),\n"
"      FortuneSlip(title:'循序渐进',description:'水到渠成，不必急于一时。一步一个脚印，终有所成。',emoji:'=',level:FortuneLevel.medium,element:'水',guardian:'玄武'),\n"
"      FortuneSlip(title:'以静制动',description:'外界纷扰，内心安定则无碍。沉稳面对，自见分明。',emoji:'@',level:FortuneLevel.medium,element:'金',guardian:'白虎'),\n"
"    ],\n"
"    FortuneLevel.low: [\n"
"      FortuneSlip(title:'阴云笼罩',description:'前路暂有阻碍，莫急躁。稍作休整，等待时机。',emoji:';',level:FortuneLevel.low,element:'土',guardian:'腾蛇'),\n"
"      FortuneSlip(title:'事需缓图',description:'时机未到，强求反累。先退一步，再谋后动。',emoji:':',level:FortuneLevel.low,element:'金',guardian:'白虎'),\n"
"      FortuneSlip(title:'静待花开',description:'好事尚需时日，耐心浇灌，静候花开。',emoji:'^',level:FortuneLevel.low,element:'木',guardian:'青龙'),\n"
"    ],\n"
"    FortuneLevel.bad: [\n"
"      FortuneSlip(title:'暗礁险滩',description:'前方有阻，慎防陷阱。低调行事，避开锋芒。',emoji:'&',level:FortuneLevel.bad,element:'水',guardian:'罗睺'),\n"
"      FortuneSlip(title:'山重水复',description:'看似无路，实则转机将至。咬牙坚持，方见光明。',emoji:'%',level:FortuneLevel.bad,element:'火',guardian:'计都'),\n"
"      FortuneSlip(title:'困顿之时',description:'黎明前最黑暗的时刻。保持信念，必有转机。',emoji:'$',level:FortuneLevel.bad,element:'木',guardian:'玄武'),\n"
"    ],\n"
"  };\n"
"}\n"
"\n"
"enum _Phase { idle, shaking, flying, reveal }\n"
)

# Replace emoji placeholders with actual unicode
content = content.replace("Text(TW", f"Text('{TW}'")
content = content.replace("Text(WV", f"Text('{WV}'")
content = content.replace("Text(SP", f"Text('{SP}'")
content = content.replace("Text(OR", f"Text('{OR}'")
content = content.replace("Text(SH", f"Text('{SH}'")

with open(FL, "w", encoding="utf-8") as f:
    f.write(content)
print(f"fate_draw_flow.dart: {len(content)} chars")

# fulfill_ceremony - just write directly with simple escapes
FC = os.path.join(BASE, "features","shop","fulfill_ceremony.dart")
# Use simple Chinese text for fireworks/celebration title
fc_title = '\u2605'  # star
fc_oracle = '\u2606'  # star

fc = (
"import 'dart:math';\n"
"import 'package:flutter/material.dart';\n"
"import 'package:kouming/shared/theme/kouming_theme.dart';\n"
"import 'package:kouming/shared/models/kouming_models.dart';\n"
"import 'package:kouming/services/i18n_service.dart';\n"
"\n"
"class FulfillCeremony extends StatefulWidget {\n"
"  final WishCapsule capsule;\n"
"  final VoidCallback onCeremonyComplete;\n"
"  const FulfillCeremony({super.key, required this.capsule, required this.onCeremonyComplete});\n"
"  static Future<void> show(BuildContext context, {required WishCapsule capsule, required VoidCallback onCeremonyComplete}) {\n"
"    return showModalBottomSheet(context:context, isScrollControlled:true, backgroundColor:Colors.transparent,\n"
"      builder:(_)=>FulfillCeremony(capsule:capsule, onCeremonyComplete:onCeremonyComplete));\n"
"  }\n"
"  @override State<FulfillCeremony> createState() => _FulfillCeremonyState();\n"
"}\n"
"\n"
"class _FulfillCeremonyState extends State<FulfillCeremony> with TickerProviderStateMixin {\n"
"  late AnimationController _glowCtrl, _fireworkCtrl;\n"
"  bool _showFireworks = false;\n"
"\n"
"  @override void initState() {\n"
"    super.initState();\n"
"    _glowCtrl = AnimationController(vsync:this, duration: const Duration(milliseconds:2000));\n"
"    _fireworkCtrl = AnimationController(vsync:this, duration: const Duration(milliseconds:3000));\n"
"  }\n"
"  @override void dispose() { _glowCtrl.dispose(); _fireworkCtrl.dispose(); super.dispose(); }\n"
"\n"
"  void _startCeremony() {\n"
"    _glowCtrl.forward().then((_){ setState(()=>_showFireworks=true); _fireworkCtrl.forward(); });\n"
"  }\n"
"\n"
"  static const Map<String,String> _catLabelKeys = {\n"
"    'study':'fulfill_cat_study','health':'fulfill_cat_health','love':'fulfill_cat_love','money':'fulfill_cat_money',\n"
"  };\n"
"\n"
"  @override Widget build(BuildContext context) {\n"
"    return Container(height:MediaQuery.of(context).size.height*0.8,\n"
"      decoration: const BoxDecoration(gradient:LinearGradient(begin:Alignment.topCenter,end:Alignment.bottomCenter,colors:[KouMingTheme.deep,KouMingTheme.mid]),\n"
"        borderRadius: BorderRadius.vertical(top:Radius.circular(24))),\n"
"      child: Stack(children:[\n"
"        Column(children:[\n"
"          Center(child:Container(margin: const EdgeInsets.only(top:10), width:40, height:4,\n"
"            decoration: BoxDecoration(color:KouMingTheme.gold.withValues(alpha:0.3), borderRadius:BorderRadius.circular(2)))),\n"
"          const SizedBox(height:16),\n"
"          Text('* ' + I18n.t('fulfill_title'), style: const TextStyle(fontSize:20,fontWeight:FontWeight.bold,color:KouMingTheme.gold,fontFamily:'MaShanZheng')),\n"
"          const SizedBox(height:20),\n"
"          Expanded(child:_buildContent()),\n"
"        ]),\n"
"        if(_showFireworks) Positioned.fill(child:IgnorePointer(child:_FireworksCanvas(animation:_fireworkCtrl))),\n"
"      ]));\n"
"  }\n"
"\n"
"  Widget _buildContent() {\n"
"    return AnimatedBuilder(animation:_glowCtrl, builder:(ctx,_){\n"
"      final t = _glowCtrl.value;\n"
"      final glowAlpha = t*0.5;\n"
"      final scale = 1.0 + t*0.1;\n"
"      return Center(child: Column(mainAxisSize:MainAxisSize.min, children:[\n"
"        Transform.scale(scale:scale, child:Container(width:120,height:120, decoration:BoxDecoration(shape:BoxShape.circle,\n"
"          gradient:RadialGradient(colors:[KouMingTheme.gold.withValues(alpha:glowAlpha+0.2),KouMingTheme.lantern.withValues(alpha:glowAlpha),KouMingTheme.purple.withValues(alpha:glowAlpha*0.5)]),\n"
"          boxShadow:[BoxShadow(color:KouMingTheme.gold.withValues(alpha:glowAlpha),blurRadius:40),BoxShadow(color:KouMingTheme.lantern.withValues(alpha:glowAlpha*0.5),blurRadius:60)]),\n"
"          child:Center(child:Text('o',style:TextStyle(fontSize:40+t*8)))))),\n"
"        const SizedBox(height:24),\n"
"        Container(padding: const EdgeInsets.symmetric(horizontal:24,vertical:12),\n"
"          decoration:BoxDecoration(color:KouMingTheme.surface.withValues(alpha:0.5), borderRadius:BorderRadius.circular(12),\n"
"            border:Border.all(color:KouMingTheme.gold.withValues(alpha:0.2))),\n"
"          child:Text('\"'+widget.capsule.wishText+'\"', style:const TextStyle(fontSize:14,fontStyle:FontStyle.italic,color:KouMingTheme.text,fontFamily:'MaShanZheng'), textAlign:TextAlign.center)),\n"
"        const SizedBox(height:8),\n"
"        Text(_getCategoryLabel(widget.capsule.category), style: const TextStyle(fontSize:13,color:KouMingTheme.dim)),\n"
"        const SizedBox(height:20),\n"
"        if(!_showFireworks)...[\n"
"          Text(I18n.t('fulfill_prompt'), style: const TextStyle(fontSize:12,color:KouMingTheme.dim)),\n"
"          const SizedBox(height:16),\n"
"          GestureDetector(onTap:_startCeremony,\n"
"            child:Container(padding: const EdgeInsets.symmetric(horizontal:28,vertical:14),\n"
"              decoration:BoxDecoration(gradient:const LinearGradient(colors:[KouMingTheme.lantern,KouMingTheme.gold]),\n"
"                borderRadius:BorderRadius.circular(24), boxShadow:[BoxShadow(color:KouMingTheme.lantern.withValues(alpha:0.3),blurRadius:12)]),\n"
"              child:Text(I18n.t('fulfill_btn'), style:const TextStyle(fontSize:15,fontWeight:FontWeight.bold,color:Color(0xFF1A1A2E))))),\n"
"        ]else...[\n"
"          const SizedBox(height:8),\n"
"          Text(I18n.t('fulfill_done'), style: const TextStyle(fontSize:18,fontWeight:FontWeight.bold,color:KouMingTheme.gold,fontFamily:'MaShanZheng')),\n"
"          const SizedBox(height:4),\n"
"          Text(I18n.t('fulfill_merit'), style: const TextStyle(fontSize:13,color:KouMingTheme.purple)),\n"
"          const SizedBox(height:16),\n"
"          GestureDetector(onTap:(){ widget.onCeremonyComplete(); Navigator.pop(context); },\n"
"            child:Container(padding: const EdgeInsets.symmetric(horizontal:24,vertical:10),\n"
"              decoration:BoxDecoration(gradient:const LinearGradient(colors:[KouMingTheme.gold,KouMingTheme.warm]), borderRadius:BorderRadius.circular(16)),\n"
"              child:Text(I18n.t('fulfill_close'), style:const TextStyle(fontSize:13,fontWeight:FontWeight.bold,color:Color(0xFF1A1A2E))))),\n"
"        ],\n"
"      ]));\n"
"    });\n"
"  }\n"
"\n"
"  String _getCategoryLabel(String cat) => I18n.t(_catLabelKeys[cat] ?? 'fulfill_cat_other');\n"
"}\n"
"\n"
"class _FireworksCanvas extends StatelessWidget {\n"
"  final Animation<double> animation;\n"
"  const _FireworksCanvas({required this.animation});\n"
"  @override Widget build(BuildContext context) {\n"
"    return AnimatedBuilder(animation:animation, builder:(ctx,_)=>CustomPaint(painter:_FireworksPainter(animation.value), size:Size.infinite));\n"
"  }\n"
"}\n"
"\n"
"class _FireworksPainter extends CustomPainter {\n"
"  final double t;\n"
"  static final _rng = Random(42);\n"
"  _FireworksPainter(this.t);\n"
"  static final List<_Burst> _bursts = [\n"
"    _Burst(0.25,0.25,KouMingTheme.gold,20,0.0), _Burst(0.75,0.20,KouMingTheme.lantern,18,0.15),\n"
"    _Burst(0.5,0.35,KouMingTheme.purple,22,0.3), _Burst(0.3,0.45,Colors.pink,16,0.45), _Burst(0.7,0.40,KouMingTheme.warm,18,0.55),\n"
"  ];\n"
"  @override void paint(Canvas c, Size s) { for(final b in _bursts) _drawBurst(c,s,b); }\n"
"  void _drawBurst(Canvas c, Size s, _Burst b) {\n"
"    if(t<b.startT) return;\n"
"    final lt = ((t-b.startT)/(1.0-b.startT)).clamp(0.0,1.0);\n"
"    final cx = s.width*b.x, cy = s.height*b.y, maxR = s.width*0.18;\n"
"    for(int i=0;i<b.count;i++){\n"
"      final angle = (i/b.count)*2*pi+_rng.nextDouble()*0.3;\n"
"      final speed = 0.5+_rng.nextDouble()*0.5;\n"
"      final pt = (lt*1.5-0.2*speed).clamp(0.0,1.0);\n"
"      if(pt<=0) continue;\n"
"      final r = maxR*pt*speed;\n"
"      final fade = pt>0.6 ? 1.0-(pt-0.6)/0.4 : 1.0;\n"
"      c.drawCircle(Offset(cx+cos(angle)*r, cy+sin(angle)*r-pt*20), 2.5*(1-pt*0.5), Paint()..color=b.color.withValues(alpha:fade*0.9));\n"
"    }\n"
"  }\n"
"  @override bool shouldRepaint(_FireworksPainter old) => t!=old.t;\n"
"}\n"
"class _Burst { final double x,y; final Color color; final int count; final double startT; _Burst(this.x,this.y,this.color,this.count,this.startT); }\n"
)

fc = fc.replace("Text('* '", f"Text('{fc_title} ")
fc = fc.replace("Text('o',", f"Text('{fc_oracle}',")

with open(FC, "w", encoding="utf-8") as f:
    f.write(fc)
print(f"fulfill_ceremony.dart: {len(fc)} chars")
